### ISSUE TITLE
isrunning() does not detect termination of short-lived processes

### ISSUE THREAD

**Issue by davidparsson** [pytest-dev/pytest-xprocess#22]
`XProcessInfo.isrunning()` is unable to detect when short-lived processes are terminated during test execution, due to https://github.com/giampaolo/psutil/issues/1008.

I'm seeing this on MacOS.

This prevents me from easily using this to execute scripts in tests and wait until they are completed.

**Comment by northernSage** [comment]
Thanks for your contribution @davidparsson 

Following is the simple test I used to reproduce what you have described  along with output for the sake of documentation.

```python
def test_short_lived_processes(xprocess):
    xprocess.ensure("short", lambda cwd: ("started", [sys.executable, short_path]))
    pid = xprocess.getinfo("short").pid
    proc = psutil.Process(pid)
    print(f"name: {proc.name()}, status: {proc.status()}")
    sleep(5)
    print(f"name: {proc.name()}, status: {proc.status()}")
    is_running = xprocess.getinfo("short").isrunning()
    print(f"xprocess.isrunning({pid}) returned {is_running}")
```
output:

> process 'short' started pid=20908
> started
> short process startup detected
> name: short-process, status: running
> name: short-process, status: zombie
> xprocess.isrunning(20908) returned True

While I can see how it could be useful in your situation, I'm not sure that considering zombies (technically still running process) as not running would be a desired general behaviour. I believe we could, however, make it so that zombies are ignored by XProcessInfo.isrunning when explicitly asked by the user. I left some suggestions in your PR, please take a look.

In case anyone wants to jump in, a second opinion would be welcome here.
