### ISSUE TITLE
When pytest exits on error (for ex Ctrl-C), xprocess terminate() does not get called

### ISSUE THREAD

**Issue by histed** [pytest-dev/pytest-xprocess#63]
With this code inside a fixture, using yield then terminate(), terminate() doesn't seem to be called when pytest exits on an error
```
    # ensure process is running and return its logfile
    logfile = xprocess.ensure("dummy_echo_server", Starter)

    yield (_address, _port)

    # clean up whole process tree afterwards
    xprocess.getinfo("dummy_echo_server").terminate()
```

How to replicate: run pytest with an xprocess fixture.  Hit Ctrl-C.  Check process: it's still running.

**Describe the solution you'd like**
Provide a way to always call terminate() on Python exit.

**Comment by northernSage** [comment]
Thanks for taking the time to open the issue @histed! 

I believe it wouldn't be too hard to implement this for interrupt signals (`SIGINT`), since teardown hooks such as [pytest_unconfigure](https://github.com/pytest-dev/pytest-xprocess/blob/master/pytest_xprocess.py#L71) are still executed after `SIGINT` during test runs (if memory doesn't fail). A possible approach would be using [XProcess.running_procs](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L98) to pass in the process name since it's already being used to pass the `Popen` instances to the[ xprocess fixture](https://github.com/pytest-dev/pytest-xprocess/blob/master/pytest_xprocess.py#L47) where they will be waited upon, and call [XProcessInfo.terminate](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L28) from there. Of course, doing so will make the manual call to [XProcessInfo.terminate](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L28) after `yield` unnecessary, since now the plugin would handle it automatically. For now, it seems like a convenient change for me, but I would like to look into it a bit more carefully (wil be able to do so in the next few days) since it will change how the fixture is used.

**Comment by histed** [comment]
Thanks. I don't have a ton of time to look into this right now but my vague memory is that Mac/Linux and Windows handle termination and signals differently.  Definitely would be great if xprocess could guarantee that spawned processes _always_ get cleaned up on pytest exit.

**Comment by northernSage** [comment]
AFAIK windows doesn't even implement POSIX-like signals at system level, it does its own thing using [APCs](https://docs.microsoft.com/en-us/windows/win32/sync/asynchronous-procedure-calls?redirectedfrom=MSDN) and the signals required by the C standard are implemented in microsoft's C runtime. That's an interesing topic but a bit out of scope here 😁

The exception handling itself will actually happen in [core pytest](url), not in `pytest-xprocess` plugin and it should be appropriately handled across different platforms. All my suggested approach does is to make use of a teardown hook to issue a termination command to all external processes started by xprocess.

> Definitely would be great if xprocess could guarantee that spawned processes always get cleaned up on pytest exit

xprocess termination currently works by first trying to recursively terminate the whole process tree gracefully with `SIGTERM` and then forcefully with `SIGKILL` (or the native platform equivalent, such as `signal.CTRL_C_EVENT` and `signal.CTRL_BREAK_EVENT` for windows, more on this [here](https://docs.python.org/3/library/os.html#os.kill)) if the previous doesn't work. Since the termination will be carried out by the host OS we can't 100% guarantee that they will always get cleaned up since there are external factors out of our control that might get in the way,  like the target process being in uninterruptible sleep state or being a zombie. What we can ensure, though, is that the termination signals will be sent before pytest exits.
